name: Build & Deploy

on:
  push:
    branches: "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js and enable npm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Install dependencies with npm
      - name: Install Dependencies
        run: npm install

      # (Optional) Run linting step
      - name: Lint Code
        run: npm run lint

      # (Optional) Run tests
      - name: Run Tests
        run: npm test

      # Build the static site
      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      # Upload artifacts for deployment
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/" # Adjust if your build output folder is different

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      # Deploy to GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
